version: "3"
services:
  app:
    build:
      context: "."
      dockerfile: "./Dockerfile"
    ports:
      - "3000:3000"
    networks:
      - jasjamjos_network
    restart: always
networks:
  jasjamjos_network:
    driver: bridge